export enum EDesignAspect {
  APPROPRIATENESS = 'APPROPRIATENESS',
  EMPHASIS = 'EMPHASIS',
  HIERARCHY = 'HIERARCHY',
  ALIGNMENT = 'ALIGNMENT',
  READABILITY = 'READABILITY',
  OVERALL = 'OVERALL',
  CONSISTENCY = 'CONSISTENCY',
}
